### ISSUE TITLE
A solution to "Too many open files" and a feature request

### ISSUE THREAD

**Issue by gitxmax** [cL0und/helloWebScan#1]
Great script, long time, I was looking for something similar.
First, it would be great to add a  few features

1. Scanning a single ip
2. Possibility to scan port ranges; -p 80-8080
3. Add a timeout option

Otherwise, works 10 out of 10
Came across a small problem, with the high -q rate, I was getting Too many open files message.
My ulimit -n was tuned before, as well as other server settings, but this seems to be python specific. Solved it, by adding this 3 lines to the script:

import resource
soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))

**Comment by cL0und** [comment]
Sorry, It's just a practice project for me, so I don't noticed your issue in a long time. Your advice is great. I have added these features.
